version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY} # Add this in Render’s environment variables
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE=laravel
      MYSQL_USER=user
      MYSQL_PASSWORD=password
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
